version: '3.8'

services:
    app:
        image: doandavid/scientists:latest
        container_name: scientists-research
        restart: unless-stopped
        ports:
            - "9000:9000"
        env_file:
            - .env.production
